version: "3.6"

services:
  api:
    build: .
    ports: 
      - "3000:3000"
    depends_on:
      - db
    environment: 
      - MONGO_URI=mongodb://db/acronym-dev
      - AUTH_TOKEN=XbPfbIHMI6arZ3Y922Bh
    networks:
      - api
    volumes: 
      - .:/app
  db:
    image: mongo
    networks:
      - api

networks:
  api: