version: "3.6"

services:
  api:
    build: .
    ports: 
      - "3000:3000"
    depends_on:
      - db
    environment: 
      - MONGODB_HOST=db
      - MONGODB_PORT=27017
      - MONGODB_DBNAME=acronym-dev
    networks:
      - api
    volumes: 
      - .:/app
  db:
    image: mongo
    networks:
      - api

networks:
  api: